### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by krittikatiwari**
In this PR I made the class and object
these are the video link
[Link 1](https://www.loom.com/share/aed1e865c80b40779d1df88c5d0ebb0c)
[Link 2](https://www.loom.com/share/d7370dfd12544a34823a7ac5f819b74b)
[Link 3](https://www.loom.com/share/559075c7be304be5b368c974dcc5637a)

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
Please book a catchup with me.

**Comment by krittikatiwari** [comment]
sure, can you please share the calendar so that I can book the slot?

**Comment by th3c0d3br34ker** [comment]
please block some time [here](https://calendar.kalvium.com/jainam-desai/30min).

**Comment by th3c0d3br34ker** [comment]
thanks @krittikatiwari, the internet connectivity was very disturbed during the viva. it rendered us impossible.

Overall feedback:

1. please consider adding more input validations in all endpoints when storing the data
2. consider splitting your `main.py` file.
3. the object instantiation is currently handled by the `FastAPI` wrapper and not by you. For future concepts, please add that explanation in the loom, so i can have the confidence that you have understood you code.

thanks, please go ahead and merge the PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
