### PR TITLE
milestone 2

### PR DESCRIPTION
**Pull request by krittikatiwari**
in this milestone i have covered to topic 
constructor and destructor 
array of object
video links are here
[link](https://www.loom.com/share/3f1c438d88c9476d956748679f0b3310)

[link 2](https://www.loom.com/share/b190489a1043498abe45bb80b6a0cd9d)

[link 3](https://www.loom.com/share/3f1c438d88c9476d956748679f0b3310])

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @krittikatiwari for you submission. the self-viva is satisfactory for `Array of Objects`. 

however for `Constructors & Destructors` the self-viva seems to incomplete. please re-check the following -- [link 2](https://www.loom.com/share/b190489a1043498abe45bb80b6a0cd9d) and let me know.

thanks

**Comment by krittikatiwari** [comment]
hey @th3c0d3br34ker ,
In the link, I have explained the destructor and it is a complete explanation for the destructor.
Please tell me in which part you think it is incomplete.

**Comment by th3c0d3br34ker** [comment]
hey @krittikatiwari please schedule a viva. I understand there is a communication gap on how to make submission.

thanks.

**Comment by th3c0d3br34ker** [comment]
approved during viva `Constructors & Destructors`. 

please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
